# Generated by Django 4.2.6 on 2023-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='no_of_guests',
        ),
        migrations.RemoveField(
            model_name='table',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='table',
            name='price',
        ),
        migrations.RemoveField(
            model_name='table',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='booking_date',
            field=models.DateTimeField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='n/a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='no_of_guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
